spring:
  application:
    name: '@project.artifactId@'
server:
  port: '8080'
feign:
  client:
    config:
      default:
        url: ${ENGINE_CAMUNDA_REST_ENDPOINT_URL}
      digiwf-process-instance:
        name: digiwf-process-instance
        url: ${ENGINE_REST_ENDPOINT_URL}
camunda:
  bpm:
    client:
      base-url: ${ENGINE_CAMUNDA_REST_ENDPOINT_URL}
      date-format: yyyy-MM-dd'T'HH:mm:ss.SSSX
de:
  muenchen:
    oss:
      digiwf:
        connector:
          core:
            integrations:
              addressIntegration: "dwf-address-${DIGIWF_ENV}"
              alwIntegration: "dwf-alw-${DIGIWF_ENV}"
              cosysIntegration: "dwf-cosys-${DIGIWF_ENV}"
              dmsIntegration: "dwf-dms-${DIGIWF_ENV}"
              emailIntegration: "dwf-email-${DIGIWF_ENV}"
              s3Integration: "dwf-s3-${DIGIWF_ENV}"
              # TODO: Remove this fallback after all processes are migrated to the new version. It's a legacy feature to avoid breaking changes.
              deprecatedLegacyFeature: ${digiwf.streaming.connector.topics.dlq}
