name: Release apps

on:
  workflow_call:
    inputs:
      publish-packages:
        description: 'Publish packages?'
        type: boolean
        required: true
        default: false
      build-images:
        description: 'Build and push images?'
        type: boolean
        required: true
        default: false
      release-version:
        description: 'Apps release version'
        type: string
        required: false

jobs:
  build-apps:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./digiwf-apps
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: "./digiwf-apps/package-lock.json"
          registry-url: 'https://registry.npmjs.org'
      - run: npm run init
      - run: npm run build

      - run: lerna publish from-package --yes
        if: inputs.publish-packages == true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Set up QEMU
        if: inputs.build-images == true
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        if: inputs.build-images == true
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        if: inputs.build-images == true
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_KEY }}

      - name: Build and push tasklist
        if: inputs.build-images == true
        uses: docker/build-push-action@v5
        with:
          context: ./digiwf-apps/packages/apps/digiwf-tasklist
          push: true
          tags: itatm/digiwf-tasklist:${{ inputs.release-version }}
